#!/bin/bash
#
# -t 'debug' or 'cloud'
# -m message
#

# !! DO NOT REMOVE THIS LINE !!
# Horse must be killed so that firereset service can be terminated successfully after upgrade
# This script is called here because this is the best place to call after this repo is upgraded
#   fireboot -> fireupgrade -> firelog -> kill horse
# Once horse is killed, this script is basically do nothing
/home/pi/firerouter/scripts/kill_horse.sh

while getopts t:m: option
do
 case "${option}"
 in
 t) DEBUG=${OPTARG};;
 m) MESSAGE=$OPTARG;;
 esac
done

if [[ -e /tmp/FWPRODUCTION ]]
then
    if [[ "$DEBUG" != "debug" ]]
    then
        /usr/bin/logger "FIREROUTER:("$DEBUG"): "$MESSAGE
        echo "$(date +'%b %d %H:%M:%S') FIREROUTER:("$DEBUG"): "$MESSAGE >> /home/pi/logs/firelog.log
    fi
else
    /usr/bin/logger "FIREROUTER:("$DEBUG"): "$MESSAGE
    echo "$(date +'%b %d %H:%M:%S') FIREROUTER:("$DEBUG"): "$MESSAGE >> /home/pi/logs/firelog.log
fi
