#!/bin/bash

execute_and_log() {
  if [ -z "$1" ]; then
    return 1
  fi
  command="$*"
  # echo "command: $command" >> /tmp/test/dhcpcd6.log
  eval "$command"
}


check_is_private_addr() {
  if [ -z "$interface" ]; then
    return 1 
  fi
  ipv4_address=$(ip -4 addr show dev "$interface" 2>/dev/null | grep -oP 'inet\s+\K[\d.]+'| head -n 1)

  if [ -z "$ipv4_address" ]; then
    return 1 
  else
    # echo "  IPv4 address for '$interface' : $ipv4_address"
    first_octet=$(echo "$ipv4_address" | cut -d'.' -f1)
    second_octet=$(echo "$ipv4_address" | cut -d'.' -f2)

    # A Class private: 10.0.0.0/8
    if [ "$first_octet" -eq 10 ]; then
      return 0 
    fi

    # B Class private: 172.16.0.0/12
    if [ "$first_octet" -eq 172 ] && [ "$second_octet" -ge 16 ] && [ "$second_octet" -le 31 ]; then
      return 0 
    fi

    # C Class private: 192.168.0.0/16
    if [ "$first_octet" -eq 192 ] && [ "$second_octet" -eq 168 ]; then
      return 0 
    fi
    return 1
  fi
  return 1
}

metric=${ifmetric:-'1024'}
mtu=${ifmtu:-'1500'}

if [ -z "$rt_tables" ]; then
    rt_tables="main"
fi

if [ -z "$default_rt_tables" ]; then
    default_rt_tables="main"
fi

ip_changed=""

case $reason in

  ROUTERADVERT)
    # If the IPv6 address of the upstream router changes, 
    # we may recieve sevaral groups of nd_* variables, take the last complete ND option set.
    nd_id=10
    nd_from=""
    while [ $nd_id -gt 0 ]; do
      nd_name="nd${nd_id}_from"
      eval "nd_from_val=\$$nd_name"
      if [ -n "$nd_from_val" ]; then
        check_is_private_addr
        RETURN_CODE=$?
        # interface to ISP should not recieve RA which only include "Route Information" from IOT gateway 
        if [ "$RETURN_CODE" -ne 0 ]; then
          nd_from="$nd_from_val"
          break
        fi

        # otherwise check other value
        nd_mtu="nd${nd_id}_mtu"
        eval "nd_mtu_val=\$$nd_mtu"
        nd_rdnss1_servers="nd${nd_id}_rdnss1_servers"
        eval "nd_rdnss1_servers_val=\$$nd_rdnss1_servers"
        nd_addr1="nd${nd_id}_addr1"
        eval "nd_addr1_val=\$$nd_addr1"
        nd_source="nd${nd_id}_source_address"
        eval "nd_source_val=\$$nd_source"
        if [ -n "$nd_mtu_val" ] || [ -n "$nd_rdnss1_servers_val" ] || [ -n "$nd_addr1_val" ] || [ -n "$nd_source_val" ]; then
          nd_from="$nd_from_val"
          break
        fi
      fi
      nd_id=$((nd_id - 1))
    done

    # If no suitable nd_from was found but only one set exists (nd1_from), use it and set nd_id=1
    if [ -z "$nd_from" ]; then
      unset ipv6_passthrough
      eval "nd1_from_val=\$nd1_from"
      if [ -n "$nd1_from_val" ]; then
        only_one=1
        check_id=2
        while [ $check_id -le 10 ]; do
          check_name="nd${check_id}_from"
          eval "check_val=\$$check_name"
          if [ -n "$check_val" ]; then
            only_one=0
            break
          fi
          check_id=$((check_id + 1))
        done
        if [ "$only_one" -eq 1 ]; then
          nd_from="$nd1_from_val"
          nd_id=1
        fi
      fi
    fi

    if [ -n "$nd_from" ]; then
      new_addrs=""
      addr_id=10
      while [ $addr_id -gt 0 ]; do
        var_name="nd${nd_id}_addr$addr_id"
        eval "addr=\$$var_name"
        if [ -n "$addr" ] && [ -z "$new_addrs" ]; then
          new_addrs="$addr"
        elif [ -n "$addr" ]; then
          # here we should take other addresses as the old addresses and remove them and related routes.
          for rt_table in $rt_tables; do
            execute_and_log "sudo ip -6 r del $addr dev $interface table $rt_table"
          done
          execute_and_log "sudo ip -6 addr del $addr dev $interface"
        fi
        addr_id=$((addr_id - 1))
      done
      if [ -n "$new_addrs" ]; then
        valid_prefix_len=64 # valid prefix length for ipv6 passthrough
        if [ -z "$ipv6_passthrough" ] || [ "${new_addrs##*/}" != "$valid_prefix_len" ]; then
          for rt_table in $rt_tables; do
            execute_and_log "sudo ip -6 r add $new_addrs dev $interface metric $metric mtu $mtu table $rt_table"
          done
        else 
          # delete dhcpcd auto-gen prefix route
          prefix_route=$(ip -6 route show dev "$interface" proto ra | grep "/${valid_prefix_len}" | awk '{print $1}' | head -n 1)
          if [ -n "$prefix_route" ]; then
            execute_and_log "sudo ip -6 r del $prefix_route dev $interface"
          fi
          
          gua_addr=$(ip -6 addr show dev "$interface" scope global | grep -oP 'inet6\s+\K[0-9a-f:]+/[0-9]+' | head -n 1)
          gua_addr_prefix_len=${gua_addr##*/}

          if [ -n "$gua_addr" ] && [ "$gua_addr_prefix_len" = "$valid_prefix_len" ]; then
            addr_only="${gua_addr%%/*}"
            execute_and_log "sudo ip -6 addr del $gua_addr dev $interface"
            execute_and_log "sudo ip -6 addr add ${addr_only}/128 dev $interface"
            #echo "$(date) changed $gua_addr to ${addr_only}/128 on $interface" >> /tmp/test/dhcpcd6.log
          fi 
        fi
      fi

      for default_rt_table in $default_rt_tables; do
        execute_and_log "sudo ip -6 r replace default via $nd_from dev $interface mtu $mtu table $default_rt_table"
      done
      old_gw=`cat /dev/shm/dhcpcd.gw6.$interface 2>/dev/null || echo ""`
      if [ "$nd_from" != "$old_gw" ]; then
        echo $nd_from > /dev/shm/dhcpcd.gw6.$interface
        ip_changed="1"
      fi
    fi

    old_addrs=`cat /dev/shm/dhcpcd.ip6.$interface 2>/dev/null || echo ""`
    if [ "$new_addrs," != "$old_addrs" ]; then
      old_addrs="${old_addrs%,}"
      if [ -n "$old_addrs" ]; then
        for rt_table in $rt_tables; do
          execute_and_log "sudo ip -6 r del $old_addrs dev $interface table $rt_table"
        done
      fi
      echo "$new_addrs," > /dev/shm/dhcpcd.ip6.$interface
      ip_changed="1"
    fi
    ;;
  BOUND6|REBOOT6)
    addr_id=1
    while [ $addr_id -lt 10 ]; do
      old_var_name="old_dhcp6_ia_na1_ia_addr$addr_id"
      eval "old_addr=\$$old_var_name"
      new_var_name="new_dhcp6_ia_na1_ia_addr$addr_id"
      status_code_name="new_dhcp6_ia_na1_ia_addr${addr_id}_status_code"
      eval "status_code=\$$status_code_name"
      if [ "$status_code" = "2" ]; then
        addr_id=$((addr_id + 1))
        continue
      fi
      eval "new_addr=\$$new_var_name"
      if [ -n "$new_addr" ]; then
        ip_changed="1"
        for rt_table in $rt_tables; do
          sudo ip -6 r add $new_addr dev $interface metric $metric mtu $mtu table $rt_table
        done
      fi
      addr_id=$((addr_id + 1))
    done
    ;;
  RENEW6|REBIND6)
    # compare old address with new address
    addr_id=1
    while [ $addr_id -lt 10 ]; do
      old_var_name="old_dhcp6_ia_na1_ia_addr$addr_id"
      eval "old_addr=\$$old_var_name"
      new_var_name="new_dhcp6_ia_na1_ia_addr$addr_id"
      eval "new_addr=\$$new_var_name"
      if [ "$old_addr" != "$new_addr" ]; then
        ip_changed="1"
      fi
      if [ -n "$new_addr" ]; then
        for rt_table in $rt_tables; do
          sudo ip -6 r add $new_addr dev $interface metric $metric mtu $mtu table $rt_table
        done
      fi
      addr_id=$((addr_id + 1))
    done
    ;;
esac

if [ -n "$ip_changed" ]; then
  redis-cli -n 1 publish "dhcpcd6.ip_change" "$interface"
fi